### 등록
POST http://localhost:8080/api/v1/issues
Content-Type: application/json

{
  "summary": "테스트2",
  "description": "본문2",
  "type": "TASK",
  "priority": "HIGH",
  "status": "TODO"
}

### 조회
GET http://localhost:8080/api/v1/issues?status=TODO

### 단건 조회
GET http://localhost:8080/api/v1/issues/1

### 수정
PUT http://localhost:8080/api/v1/issues/1
Content-Type: application/json

{
  "summary": "수정한 제목",
  "description": "수정한 본문",
  "type": "BUG",
  "priority": "LOW",
  "status": "IN_PROGRESS"
}

### 삭제
DELETE http://localhost:8080/api/v1/issues/1

## 코멘트
### 등록
POST http://localhost:8080/api/v1/issues/1/comment
Content-Type: application/json

{
  "body": "할룽3"
}

### 수정
PUT http://localhost:8080/api/v1/issues/1/comment/1
Content-Type: application/json

{
  "body": "수정된 할룽"
}